baseurl = "/"
disableAliases = true
disableHugoGeneratorInject = true
enableEmoji = true
enableGitInfo = false
enableRobotsTXT = true
languageCode = "en"
paginate = 7
rssLimit = 10

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true

# add redirects/headers
[outputs]
home = ["HTML", "RSS", "REDIRECTS", "HEADERS"]
section = ["HTML", "RSS", "SITEMAP"]

# remove .{ext} from text/netlify
[mediaTypes."text/netlify"]
suffixes = [""]
delimiter = ""

# add output format for netlify _redirects
[outputFormats.REDIRECTS]
mediaType = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true

# add output format for netlify _headers
[outputFormats.HEADERS]
mediaType = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true

# add output format for section sitemap.xml
[outputFormats.SITEMAP]
mediaType = "application/xml"
baseName = "sitemap"
isHTML = false
isPlainText = true
noUgly = true
rel  = "sitemap"

[languages]
[languages.en]
title = "Salvo"
description = "Salvo is a powerful and simplest web server framework in Rust world"
languageName ="English"
contentDir = "content/en"
# Weight used for sorting.
weight = 1
[languages.zh-hans]
title = "Salvo"
description = "Salvo 是一个简单易用的 Rust Web 后端框架. 仅仅需要基本的 Rust 基础即可写成功能强大的后端服务器, 我们的目标是: 编码很简单, 功能不缺失, 性能有保障."
languageName ="简体中文"
contentDir = "content/zh-hans"
time_format_default = "2006/02/01"
time_format_blog = "2006/02/01"
[languages.zh-hant]
title = "Salvo"
description = "Salvo 是一個簡單易用的 Rust Web 後端框架. 僅僅需要基本的 Rust 基礎即可寫成功能強大的後端服務器, 我們的目標是: 編碼很簡單, 功能不缺失, 性能有保障."
languageName ="繁体中文"
contentDir = "content/zh-hant"
time_format_default = "2006/02/01"
time_format_blog = "2006/02/01"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      linkify = false
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    style = "dracula"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[module]
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "node_modules/lazysizes"
    target = "assets/js/vendor/lazysizes"
  [[module.mounts]]
    source = "node_modules/instant.page"
    target = "assets/js/vendor/instant.page"
  [[module.mounts]]
    source = "node_modules/flexsearch"
    target = "assets/js/vendor/flexsearch"
  [[module.mounts]]
    source = "node_modules/clipboard"
    target = "assets/js/vendor/clipboard"