[build]
  publish = "public"
  functions = "functions"

[build.environment]
  HUGO_VERSION = "0.97.3"
  HUGO_ENABLEGITINFO = "true"
  HUGO_ENV = "production"
  NODE_VERSION = "18.0.0"
  NPM_VERSION = "8.7.0"

[context.production]
  command = "hugo -b $URL --gc --minify && npm run build:functions"

[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL --gc --minify"

[context.branch-deploy]
  command = "hugo -b $DEPLOY_PRIME_URL --gc --minify"
