[package]
name = "example-handle-error"
version = "0.1.0"
edition = "2021"
publish = false


[dependencies]
anyhow = "1"
salvo = { git = "https://github.com/salvo-rs/salvo.git", features = ["anyhow"] }
tokio = { version = "1", features = ["macros"] }
tracing = "0.1"
tracing-subscriber = "0.3"
