name: ci-linux

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - next

jobs:
  check:
    strategy:
        fail-fast: false
        matrix:
          version:
            - stable
            # - nightly
    name: Cargo check ${{ matrix.version }} - x86_64-unknown-linux-gnu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.version }}
          components: rustfmt, clippy

      - name: check build
        run: cargo check --all --bins --examples --tests

      - name: check release build
        run: cargo check --all --bins --examples --tests --release